language: bash

services:
- docker

jobs:
  include:
  - stage: build
    if: (tag IS NOT present)
    script:
    - env
    - docker build --build-arg TRAVIS=${TRAVIS} --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID} --target BUILD .
